#import <UIKit/UIKit.h>
#import <AVFoundation/AVFoundation.h>
#import <objc/runtime.h>
#import <math.h>

static BOOL gTikTokMuted=YES;
static float gTikTokVolume=0.0f;
static UIButton *gMuteButton;
static UIView *gVolumePanel;
static UISlider *gVolumeSlider;
static UILabel *gVolumeLabel;
static id gAudioTarget;
static NSHashTable *gAudioObjects;
static NSMapTable *gBaseVolumes;
static NSMapTable *gBaseTrackEnabled;
static NSMutableDictionary *gOriginals;
static BOOL gInternalChange=NO;

static BOOL IsTikTok(void){NSString*b=NSBundle.mainBundle.bundleIdentifier.lowercaseString;return [b containsString:@"tiktok"]||[b containsString:@"musically"];}
static NSString*HookKey(Class c,SEL s){return [NSString stringWithFormat:@"%p:%@",c,NSStringFromSelector(s)];}
static IMP OriginalFor(id obj,SEL sel){Class c=object_getClass(obj);while(c){NSValue*v=gOriginals[HookKey(c,sel)];if(v){IMP p=NULL;[v getValue:&p];return p;}c=class_getSuperclass(c);}return NULL;}
static void KeepMixing(void){if(!IsTikTok())return;AVAudioSession*s=AVAudioSession.sharedInstance;NSString*c=s.category;if(!c.length)c=AVAudioSessionCategoryPlayback;[s setCategory:c mode:s.mode options:s.categoryOptions|AVAudioSessionCategoryOptionMixWithOthers error:nil];}
static void MuteObject(id o){if(!o||!gTikTokMuted)return;gInternalChange=YES;if([o respondsToSelector:@selector(setMuted:)])[o setMuted:YES];if([o respondsToSelector:@selector(setVolume:)])[o setVolume:0.0f];if([o respondsToSelector:@selector(setOutputVolume:)])[o setOutputVolume:0.0f];gInternalChange=NO;}
static void RestoreObject(id o){if(!o||gTikTokMuted)return;gInternalChange=YES;if([o respondsToSelector:@selector(setMuted:)])[o setMuted:NO];float base=1.0f;NSNumber*n=[gBaseVolumes objectForKey:o];if(n)base=n.floatValue;float v=MAX(0.0f,MIN(1.0f,base*gTikTokVolume));IMP p=OriginalFor(o,@selector(setVolume:));if(p)((void(*)(id,SEL,float))p)(o,@selector(setVolume:),v);IMP q=OriginalFor(o,@selector(setOutputVolume:));if(q)((void(*)(id,SEL,float))q)(o,@selector(setOutputVolume:),v);gInternalChange=NO;}
static void ApplyMuteState(void){for(id o in gAudioObjects.allObjects){if(gTikTokMuted)MuteObject(o);else RestoreObject(o);}for(AVPlayerItemTrack*t in gBaseTrackEnabled.keyEnumerator){NSNumber*n=[gBaseTrackEnabled objectForKey:t];if(n)t.enabled=gTikTokMuted?NO:n.boolValue;}}
static void UpdateUI(void){dispatch_async(dispatch_get_main_queue(),^{NSInteger p=(NSInteger)lrintf(gTikTokVolume*100.0f);[gMuteButton setTitle:gTikTokMuted?@"🔇  MUTED":@"🔊  TIKTOK" forState:UIControlStateNormal];gVolumeSlider.value=gTikTokVolume;gVolumeLabel.text=[NSString stringWithFormat:@"TikTok volume: %ld%%",(long)p];});}
void TikTokPlusSetMuted(BOOL muted){if(!IsTikTok())return;if(muted){gTikTokMuted=YES;gTikTokVolume=0.0f;}else{if(gTikTokVolume<=0.001f)gTikTokVolume=1.0f;gTikTokMuted=NO;}KeepMixing();ApplyMuteState();UpdateUI();[[NSNotificationCenter defaultCenter]postNotificationName:@"TikTokPlusMuteChanged" object:nil userInfo:@{@"muted":@(gTikTokMuted),@"volume":@(gTikTokVolume)}];}
static void SetTikTokVolume(float v){if(!IsTikTok())return;gTikTokVolume=MAX(0.0f,MIN(1.0f,v));gTikTokMuted=gTikTokVolume<=0.001f;KeepMixing();ApplyMuteState();UpdateUI();[[NSNotificationCenter defaultCenter]postNotificationName:@"TikTokPlusMuteChanged" object:nil userInfo:@{@"muted":@(gTikTokMuted),@"volume":@(gTikTokVolume)}];}
@interface TTKPlusAudioTarget:NSObject@end
@implementation TTKPlusAudioTarget
-(void)tapMute:(id)sender{TikTokPlusSetMuted(!gTikTokMuted);gVolumePanel.hidden=NO;}
-(void)sliderChanged:(UISlider*)s{SetTikTokVolume(s.value);}
-(void)closePanel:(id)sender{gVolumePanel.hidden=YES;}
-(void)muteFromPanel:(id)sender{TikTokPlusSetMuted(YES);}
@end
static UIWindow*HostWindow(void){UIApplication*a=UIApplication.sharedApplication;for(UIScene*s in a.connectedScenes)if(s.activationState==UISceneActivationStateForegroundActive&&[s isKindOfClass:UIWindowScene.class])for(UIWindow*w in ((UIWindowScene*)s).windows)if(!w.hidden&&w.alpha>0.01&&w.windowLevel==UIWindowLevelNormal&&w.rootViewController&&w.isKeyWindow)return w;for(UIScene*s in a.connectedScenes)if(s.activationState==UISceneActivationStateForegroundActive&&[s isKindOfClass:UIWindowScene.class])for(UIWindow*w in ((UIWindowScene*)s).windows)if(!w.hidden&&w.alpha>0.01&&w.windowLevel==UIWindowLevelNormal&&w.rootViewController)return w;return nil;}
static void InstallPanel(UIWindow*h){if(!h)return;if(!gAudioTarget)gAudioTarget=[TTKPlusAudioTarget new];if(!gVolumePanel){UIView*p=[[UIView alloc]initWithFrame:CGRectZero];p.backgroundColor=[[UIColor blackColor]colorWithAlphaComponent:.92];p.layer.cornerRadius=14;p.layer.borderWidth=1;p.layer.borderColor=UIColor.whiteColor.CGColor;p.hidden=YES;UILabel*t=[[UILabel alloc]initWithFrame:CGRectZero];t.tag=1;t.text=@"TikTok Volume";t.textColor=UIColor.whiteColor;t.font=[UIFont boldSystemFontOfSize:15];t.textAlignment=NSTextAlignmentCenter;[p addSubview:t];gVolumeLabel=[[UILabel alloc]initWithFrame:CGRectZero];gVolumeLabel.tag=2;gVolumeLabel.textColor=UIColor.whiteColor;gVolumeLabel.textAlignment=NSTextAlignmentCenter;[p addSubview:gVolumeLabel];gVolumeSlider=[[UISlider alloc]initWithFrame:CGRectZero];gVolumeSlider.tag=3;gVolumeSlider.minimumValue=0;gVolumeSlider.maximumValue=1;[gVolumeSlider addTarget:gAudioTarget action:@selector(sliderChanged:) forControlEvents:UIControlEventValueChanged];[p addSubview:gVolumeSlider];UIButton*m=[UIButton buttonWithType:UIButtonTypeSystem];m.tag=4;[m setTitle:@"MUTE" forState:UIControlStateNormal];[m setTitleColor:UIColor.whiteColor forState:UIControlStateNormal];[m addTarget:gAudioTarget action:@selector(muteFromPanel:) forControlEvents:UIControlEventTouchUpInside];[p addSubview:m];UIButton*d=[UIButton buttonWithType:UIButtonTypeSystem];d.tag=5;[d setTitle:@"DONE" forState:UIControlStateNormal];[d setTitleColor:UIColor.whiteColor forState:UIControlStateNormal];[d addTarget:gAudioTarget action:@selector(closePanel:) forControlEvents:UIControlEventTouchUpInside];[p addSubview:d];gVolumePanel=p;[h addSubview:p];}if(gVolumePanel.superview!=h){[gVolumePanel removeFromSuperview];[h addSubview:gVolumePanel];}CGFloat w=270;gVolumePanel.frame=CGRectMake(MAX(8,(h.bounds.size.width-w)/2),MAX(h.safeAreaInsets.top+58,100),w,126);for(UIView*v in gVolumePanel.subviews)switch(v.tag){case 1:v.frame=CGRectMake(10,8,w-20,22);break;case 2:v.frame=CGRectMake(10,30,w-20,20);break;case 3:v.frame=CGRectMake(16,51,w-32,30);break;case 4:v.frame=CGRectMake(16,88,112,28);break;case 5:v.frame=CGRectMake(w-128,88,112,28);break;}UpdateUI();[h bringSubviewToFront:gVolumePanel];}
static void InstallMuteButton(void){dispatch_async(dispatch_get_main_queue(),^{if(!IsTikTok())return;UIWindow*h=HostWindow();if(!h)return;InstallPanel(h);if(!gMuteButton||gMuteButton.superview!=h){[gMuteButton removeFromSuperview];gMuteButton=[UIButton buttonWithType:UIButtonTypeSystem];gMuteButton.tag=190611;gMuteButton.backgroundColor=[[UIColor blackColor]colorWithAlphaComponent:.86];gMuteButton.layer.cornerRadius=12;gMuteButton.layer.borderWidth=1;gMuteButton.layer.borderColor=UIColor.whiteColor.CGColor;[gMuteButton setTitleColor:UIColor.whiteColor forState:UIControlStateNormal];gMuteButton.titleLabel.font=[UIFont boldSystemFontOfSize:13];gMuteButton.accessibilityLabel=@"TikTok audio mute";[gMuteButton addTarget:gAudioTarget action:@selector(tapMute:) forControlEvents:UIControlEventTouchUpInside];[h addSubview:gMuteButton];}CGFloat w=112;gMuteButton.frame=CGRectMake(MAX(8,h.bounds.size.width-w-12),MAX(h.safeAreaInsets.top+10,44),w,44);gMuteButton.hidden=NO;[h bringSubviewToFront:gMuteButton];if(!gVolumePanel.hidden)[h bringSubviewToFront:gVolumePanel];UpdateUI();});}
void TikTokPlusInstallMuteButton(void){InstallMuteButton();}
static void SaveHook(Class c,SEL s,IMP r){if(!c||!r)return;Method m=class_getInstanceMethod(c,s);if(!m)return;NSString*k=HookKey(c,s);if(gOriginals[k])return;IMP o=method_getImplementation(m);gOriginals[k]=[NSValue valueWithBytes:&o objCType:@encode(IMP)];method_setImplementation(m,r);}
static void HookPlay(id self,SEL sel){[gAudioObjects addObject:self];IMP o=OriginalFor(self,sel);if(o)((void(*)(id,SEL))o)(self,sel);if(gTikTokMuted)MuteObject(self);else RestoreObject(self);}
static void HookMuted(id self,SEL sel,BOOL v){[gAudioObjects addObject:self];if(gTikTokMuted)v=YES;IMP o=OriginalFor(self,sel);if(o)((void(*)(id,SEL,BOOL))o)(self,sel,v);if(gTikTokMuted)MuteObject(self);}
static void HookVolume(id self,SEL sel,float v){[gAudioObjects addObject:self];if(!gInternalChange&&!gTikTokMuted)[gBaseVolumes setObject:@(v) forKey:self];float out=gTikTokMuted?0.0f:v*gTikTokVolume;IMP o=OriginalFor(self,sel);if(o)((void(*)(id,SEL,float))o)(self,sel,out);}
static void HookOutputVolume(id self,SEL sel,float v){[gAudioObjects addObject:self];if(!gInternalChange&&!gTikTokMuted)[gBaseVolumes setObject:@(v) forKey:self];float out=gTikTokMuted?0.0f:v*gTikTokVolume;IMP o=OriginalFor(self,sel);if(o)((void(*)(id,SEL,float))o)(self,sel,out);}
static void HookMixVolume(id self,SEL sel,float v){float out=gTikTokMuted?0.0f:v*gTikTokVolume;IMP o=OriginalFor(self,sel);if(o)((void(*)(id,SEL,float))o)(self,sel,out);}
static void HookAudioMix(id self,SEL sel,AVAudioMix*mix){IMP o=OriginalFor(self,sel);if(!o)return;if(!mix){((void(*)(id,SEL,AVAudioMix*))o)(self,sel,mix);return;}AVMutableAudioMix*z=[AVMutableAudioMix audioMix];NSMutableArray*a=[NSMutableArray array];float scale=gTikTokMuted?0.0f:gTikTokVolume;for(AVAudioMixInputParameters*p in mix.inputParameters){AVMutableAudioMixInputParameters*q=[p mutableCopy];[q setVolume:scale atTime:kCMTimeZero];[a addObject:q];}z.inputParameters=a;((void(*)(id,SEL,AVAudioMix*))o)(self,sel,z);}
static NSArray*HookTracks(id self,SEL sel){IMP o=OriginalFor(self,sel);NSArray*a=o?((NSArray*(*)(id,SEL))o)(self,sel):nil;for(AVPlayerItemTrack*t in a)if(t.assetTrack&&[t.assetTrack.mediaType isEqualToString:AVMediaTypeAudio]){if(![gBaseTrackEnabled objectForKey:t])[gBaseTrackEnabled setObject:@(t.enabled) forKey:t];NSNumber*n=[gBaseTrackEnabled objectForKey:t];t.enabled=gTikTokMuted?NO:n.boolValue;}return a;}
static void HookSession(id self,SEL sel,NSString*cat,AVAudioSessionCategoryOptions opt,NSError**err){IMP o=OriginalFor(self,sel);if(o)((BOOL(*)(id,SEL,NSString*,AVAudioSessionCategoryOptions,NSError**))o)(self,sel,cat,opt|AVAudioSessionCategoryOptionMixWithOthers,err);}
static void InstallHooks(void){SaveHook([AVPlayer class],@selector(play),(IMP)HookPlay);SaveHook([AVPlayer class],@selector(setMuted:),(IMP)HookMuted);SaveHook([AVPlayer class],@selector(setVolume:),(IMP)HookVolume);SaveHook([AVAudioPlayer class],@selector(play),(IMP)HookPlay);SaveHook([AVAudioPlayer class],@selector(setVolume:),(IMP)HookVolume);SaveHook([AVAudioPlayerNode class],@selector(play),(IMP)HookPlay);SaveHook([AVAudioPlayerNode class],@selector(setVolume:),(IMP)HookVolume);SaveHook([AVAudioMixerNode class],@selector(setOutputVolume:),(IMP)HookOutputVolume);SaveHook([AVAudioEnvironmentNode class],@selector(setOutputVolume:),(IMP)HookOutputVolume);Class r=NSClassFromString(@"AVSampleBufferAudioRenderer");SaveHook(r,@selector(play),(IMP)HookPlay);SaveHook(r,@selector(setMuted:),(IMP)HookMuted);SaveHook(r,@selector(setVolume:),(IMP)HookVolume);SaveHook(NSClassFromString(@"AVMutableAudioMixInputParameters"),@selector(setVolume:),(IMP)HookMixVolume);SaveHook([AVAudioSession class],@selector(setCategory:withOptions:error:),(IMP)HookSession);SaveHook(NSClassFromString(@"AVPlayerItem"),@selector(setAudioMix:),(IMP)HookAudioMix);SaveHook(NSClassFromString(@"AVPlayerItem"),@selector(tracks),(IMP)HookTracks);}
%ctor{if(!IsTikTok())return;gAudioObjects=[NSHashTable weakObjectsHashTable];gBaseVolumes=[NSMapTable weakToStrongObjectsMapTable];gBaseTrackEnabled=[NSMapTable weakToStrongObjectsMapTable];gOriginals=[NSMutableDictionary dictionary];InstallHooks();KeepMixing();dispatch_async(dispatch_get_main_queue(),^{InstallMuteButton();[[NSNotificationCenter defaultCenter]addObserverForName:UIApplicationDidBecomeActiveNotification object:nil queue:NSOperationQueue.mainQueue usingBlock:^(NSNotification*n){KeepMixing();ApplyMuteState();InstallMuteButton();}];[[NSNotificationCenter defaultCenter]addObserverForName:UIWindowDidBecomeKeyNotification object:nil queue:NSOperationQueue.mainQueue usingBlock:^(NSNotification*n){InstallMuteButton();}];[[NSNotificationCenter defaultCenter]addObserverForName:UISceneDidActivateNotification object:nil queue:NSOperationQueue.mainQueue usingBlock:^(NSNotification*n){InstallMuteButton();}];});dispatch_source_t t=dispatch_source_create(DISPATCH_SOURCE_TYPE_TIMER,0,0,dispatch_get_main_queue());dispatch_source_set_timer(t,dispatch_time(DISPATCH_TIME_NOW,NSEC_PER_MSEC*200),NSEC_PER_MSEC*500,NSEC_PER_MSEC*100);__block int n=0;dispatch_source_set_event_handler(t,^{InstallHooks();KeepMixing();ApplyMuteState();InstallMuteButton();if(++n>=30)dispatch_source_cancel(t);});dispatch_resume(t);}