#import <UIKit/UIKit.h>
#import <AVFoundation/AVFoundation.h>
#import <objc/runtime.h>
static BOOL gTikTokMuted=NO;static UIButton*gMuteButton;static id gAudioTarget;static UIWindow*gMuteWindow;static NSHashTable*gPlayers;static NSHashTable*gAudioObjects;static NSMutableDictionary*gAVOriginals;
static BOOL IsTikTok(void){NSString*b=[NSBundle mainBundle].bundleIdentifier.lowercaseString;return[b containsString:@"musically"]||[b containsString:@"tiktok"];}
static UIWindowScene*ActiveScene(void){if(@available(iOS 13.0,*)){for(UIScene*s in UIApplication.sharedApplication.connectedScenes)if([s isKindOfClass:UIWindowScene.class]&&s.activationState==UISceneActivationStateForegroundActive)return(UIWindowScene*)s;}return nil;}
static NSString*AVKey(Class c,SEL s){return[NSString stringWithFormat:@"%p:%@",c,NSStringFromSelector(s)];}static IMP AVOriginal(id self,SEL sel){Class c=object_getClass(self);while(c){NSValue*v=gAVOriginals[AVKey(c,sel)];if(v){IMP p=NULL;[v getValue:&p];return p;}c=class_getSuperclass(c);}return NULL;}
static void EnsureBackgroundMusicMixing(void){if(!IsTikTok())return;AVAudioSession*s=AVAudioSession.sharedInstance;AVAudioSessionCategoryOptions o=s.categoryOptions;if(o&AVAudioSessionCategoryOptionMixWithOthers)return;NSString*c=s.category;if(!c.length)return;NSError*e=nil;BOOL ok=[s setCategory:c mode:s.mode options:o|AVAudioSessionCategoryOptionMixWithOthers error:&e];if(!ok&&[c isEqualToString:AVAudioSessionCategorySoloAmbient])[s setCategory:AVAudioSessionCategoryAmbient mode:s.mode options:o|AVAudioSessionCategoryOptionMixWithOthers error:nil];}
static void ForceMuteObject(id o){if(!o||!gTikTokMuted)return;if([o respondsToSelector:@selector(setMuted:)])[o setMuted:YES];if([o respondsToSelector:@selector(setVolume:)])[o setVolume:0.0f];if([o respondsToSelector:@selector(setOutputVolume:)])[o setOutputVolume:0.0f];}static void ApplyMuteState(void){if(!gTikTokMuted)return;for(id o in gPlayers.allObjects)ForceMuteObject(o);for(id o in gAudioObjects.allObjects)ForceMuteObject(o);}
void TikTokPlusSetMuted(BOOL muted){if(!IsTikTok())return;gTikTokMuted=muted;dispatch_async(dispatch_get_main_queue(),^{[gMuteButton setTitle:muted?@"UNMUTE":@"MUTE" forState:UIControlStateNormal];});EnsureBackgroundMusicMixing();ApplyMuteState();[[NSNotificationCenter defaultCenter]postNotificationName:@"TikTokPlusMuteChanged" object:nil userInfo:@{@"muted":@(muted)}];}
@interface TTKPlusAudioTarget:NSObject@end @implementation TTKPlusAudioTarget -(void)tapMute:(id)sender{TikTokPlusSetMuted(!gTikTokMuted);}@end
@interface TTKPassthroughWindow:UIWindow@end @implementation TTKPassthroughWindow -(UIView*)hitTest:(CGPoint)p withEvent:(UIEvent*)e{UIView*v=[super hitTest:p withEvent:e];if(v==self.rootViewController.view)return nil;return v;}@end
static void InstallMuteButton(void){dispatch_async(dispatch_get_main_queue(),^{if(!IsTikTok())return;UIWindowScene*scene=ActiveScene();if(!scene)return;if(!gAudioTarget)gAudioTarget=[TTKPlusAudioTarget new];if(!gMuteWindow){gMuteWindow=[[TTKPassthroughWindow alloc]initWithWindowScene:scene];gMuteWindow.backgroundColor=UIColor.clearColor;gMuteWindow.windowLevel=UIWindowLevelAlert+1;gMuteWindow.rootViewController=[UIViewController new];gMuteWindow.rootViewController.view.backgroundColor=UIColor.clearColor;}else if(gMuteWindow.windowScene!=scene)gMuteWindow.windowScene=scene;gMuteWindow.frame=scene.coordinateSpace.bounds;if(!gMuteButton){UIButton*b=[UIButton buttonWithType:UIButtonTypeSystem];b.backgroundColor=[[UIColor blackColor]colorWithAlphaComponent:.82];b.layer.cornerRadius=10;[b setTitle:gTikTokMuted?@"UNMUTE":@"MUTE" forState:UIControlStateNormal];[b setTitleColor:UIColor.whiteColor forState:UIControlStateNormal];b.titleLabel.font=[UIFont boldSystemFontOfSize:14];[b addTarget:gAudioTarget action:@selector(tapMute:) forControlEvents:UIControlEventTouchUpInside];[gMuteWindow.rootViewController.view addSubview:b];gMuteButton=b;}gMuteButton.frame=CGRectMake(MAX(8,gMuteWindow.bounds.size.width-110),60,96,42);gMuteButton.hidden=NO;gMuteButton.alpha=1;gMuteWindow.hidden=NO;});}
void TikTokPlusInstallMuteButton(void){InstallMuteButton();}
static void SaveAndHook(Class c,SEL s,IMP r){if(!c||!r)return;Method m=class_getInstanceMethod(c,s);if(!m)return;NSString*k=AVKey(c,s);if(gAVOriginals[k])return;IMP o=method_getImplementation(m);gAVOriginals[k]=[NSValue valueWithBytes:&o objCType:@encode(IMP)];method_setImplementation(m,r);}
static void TTKPlay(id self,SEL c){[gPlayers addObject:self];if(gTikTokMuted)ForceMuteObject(self);IMP o=AVOriginal(self,c);if(o)((void(*)(id,SEL))o)(self,c);if(gTikTokMuted)ForceMuteObject(self);}static void TTKSetMuted(id self,SEL c,BOOL v){if(gTikTokMuted)v=YES;IMP o=AVOriginal(self,c);if(o)((void(*)(id,SEL,BOOL))o)(self,c,v);}static void TTKSetVolume(id self,SEL c,float v){if(gTikTokMuted)v=0;IMP o=AVOriginal(self,c);if(o)((void(*)(id,SEL,float))o)(self,c,v);}static void TTKEngine(id self,SEL c,NSError**e){IMP o=AVOriginal(self,c);if(o)((BOOL(*)(id,SEL,NSError**))o)(self,c,e);if(gTikTokMuted&&[self respondsToSelector:@selector(mainMixerNode)])[[self mainMixerNode]setOutputVolume:0];}
static void InstallAVHooks(void){SaveAndHook(NSClassFromString(@"AVPlayer"),@selector(play),(IMP)TTKPlay);SaveAndHook(NSClassFromString(@"AVPlayer"),@selector(setMuted:),(IMP)TTKSetMuted);SaveAndHook(NSClassFromString(@"AVPlayer"),@selector(setVolume:),(IMP)TTKSetVolume);SaveAndHook(NSClassFromString(@"AVAudioPlayer"),@selector(play),(IMP)TTKPlay);SaveAndHook(NSClassFromString(@"AVAudioPlayer"),@selector(setVolume:),(IMP)TTKSetVolume);SaveAndHook(NSClassFromString(@"AVAudioPlayerNode"),@selector(play),(IMP)TTKPlay);SaveAndHook(NSClassFromString(@"AVAudioMixerNode"),@selector(setOutputVolume:),(IMP)TTKSetVolume);SaveAndHook(NSClassFromString(@"AVAudioEnvironmentNode"),@selector(setOutputVolume:),(IMP)TTKSetVolume);SaveAndHook(NSClassFromString(@"AVSampleBufferAudioRenderer"),@selector(play),(IMP)TTKPlay);SaveAndHook(NSClassFromString(@"AVSampleBufferAudioRenderer"),@selector(setMuted:),(IMP)TTKSetMuted);SaveAndHook(NSClassFromString(@"AVSampleBufferAudioRenderer"),@selector(setVolume:),(IMP)TTKSetVolume);SaveAndHook(NSClassFromString(@"AVAudioEngine"),@selector(startAndReturnError:),(IMP)TTKEngine);}
%ctor{if(!IsTikTok())return;gPlayers=[NSHashTable weakObjectsHashTable];gAudioObjects=[NSHashTable weakObjectsHashTable];gAVOriginals=[NSMutableDictionary dictionary];InstallAVHooks();EnsureBackgroundMusicMixing();dispatch_async(dispatch_get_main_queue(),^{InstallMuteButton();[[NSNotificationCenter defaultCenter]addObserverForName:UIApplicationDidBecomeActiveNotification object:nil queue:NSOperationQueue.mainQueue usingBlock:^(NSNotification*n){InstallMuteButton();}];});dispatch_source_t t=dispatch_source_create(DISPATCH_SOURCE_TYPE_TIMER,0,0,dispatch_get_main_queue());dispatch_source_set_timer(t,dispatch_time(DISPATCH_TIME_NOW,NSEC_PER_SEC),NSEC_PER_SEC,100*NSEC_PER_MSEC);dispatch_source_set_event_handler(t,^{InstallAVHooks();InstallMuteButton();EnsureBackgroundMusicMixing();if(gTikTokMuted)ApplyMuteState();});dispatch_resume(t);}
