#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import <objc/runtime.h>
#import <objc/message.h>

void TikTokPlusInstallMuteButton(void);
static BOOL gPrivateTikTokMuted=NO;
static __weak id gCurrentFeedCell;
static __weak id gCurrentPlayerController;
static __weak id gCurrentPlayer;
static NSMutableDictionary *gOriginalIMPs;

static BOOL PTIsTikTok(void){return [[[NSBundle mainBundle] bundleIdentifier] isEqualToString:@"com.zhiliaoapp.musically"];}
static NSString *PTKey(Class cls,SEL sel){return [NSString stringWithFormat:@"%p:%@",cls,NSStringFromSelector(sel)];}
static IMP PTOriginal(Class cls,SEL sel){NSValue *v=gOriginalIMPs[PTKey(cls,sel)];if(!v)return NULL;IMP p=NULL;[v getValue:&p];return p;}
static IMP PTOriginalForSelf(id self,SEL sel){Class cls=object_getClass(self);while(cls){IMP p=PTOriginal(cls,sel);if(p)return p;cls=class_getSuperclass(cls);}return NULL;}
static void PTForceObject(id o){if(!o||!gPrivateTikTokMuted)return;if([o respondsToSelector:@selector(setMuted:)])((void(*)(id,SEL,BOOL))objc_msgSend)(o,@selector(setMuted:),YES);if([o respondsToSelector:@selector(setMute:)])((void(*)(id,SEL,BOOL))objc_msgSend)(o,@selector(setMute:),YES);if([o respondsToSelector:@selector(setAudioMuted:)])((void(*)(id,SEL,BOOL))objc_msgSend)(o,@selector(setAudioMuted:),YES);if([o respondsToSelector:@selector(setVolume:)])((void(*)(id,SEL,float))objc_msgSend)(o,@selector(setVolume:),0.0f);if([o respondsToSelector:@selector(setAudioVolume:)])((void(*)(id,SEL,float))objc_msgSend)(o,@selector(setAudioVolume:),0.0f);if([o respondsToSelector:@selector(setPlayerVolume:)])((void(*)(id,SEL,float))objc_msgSend)(o,@selector(setPlayerVolume:),0.0f);if([o respondsToSelector:@selector(mute)])((void(*)(id,SEL))objc_msgSend)(o,@selector(mute));}
static void PTScanObject(id root,NSInteger depth){if(!root||depth>4||!gPrivateTikTokMuted)return;PTForceObject(root);Class cls=object_getClass(root);unsigned int n=0;Ivar *iv=class_copyIvarList(cls,&n);for(unsigned int i=0;i<n;i++){const char*t=ivar_getTypeEncoding(iv[i]);if(!t||t[0]!='@')continue;id c=object_getIvar(root,iv[i]);if(!c||c==root)continue;if([c isKindOfClass:[NSArray class]])for(id x in c)PTScanObject(x,depth+1);else if([c isKindOfClass:[NSSet class]])for(id x in c)PTScanObject(x,depth+1);else if([c isKindOfClass:[NSDictionary class]])for(id x in [c allValues])PTScanObject(x,depth+1);else PTScanObject(c,depth+1);}free(iv);}
static void PTInstall(Class cls,SEL sel,IMP replacement){if(!cls||!replacement)return;Method m=class_getInstanceMethod(cls,sel);if(!m)return;NSString*k=PTKey(cls,sel);if(gOriginalIMPs[k])return;IMP original=method_getImplementation(m);gOriginalIMPs[k]=[NSValue valueWithBytes:&original objCType:@encode(IMP)];method_setImplementation(m,replacement);}
static void PTSetBool(id self,SEL sel,BOOL value){if(gPrivateTikTokMuted)value=YES;IMP o=PTOriginalForSelf(self,sel);if(o)((void(*)(id,SEL,BOOL))o)(self,sel,value);}
static void PTSetFloat(id self,SEL sel,float value){if(gPrivateTikTokMuted)value=0.0f;IMP o=PTOriginalForSelf(self,sel);if(o)((void(*)(id,SEL,float))o)(self,sel,value);}
static void PTMute(id self,SEL sel){IMP o=PTOriginalForSelf(self,sel);if(o)((void(*)(id,SEL))o)(self,sel);}
static void PTPlayerLoop(id self,SEL sel,id player){gCurrentPlayerController=self;gCurrentPlayer=player;IMP o=PTOriginalForSelf(self,sel);if(o)((void(*)(id,SEL,id))o)(self,sel,player);TikTokPlusInstallMuteButton();if(gPrivateTikTokMuted){PTForceObject(self);PTScanObject(player,0);}}
static void PTFeedDisplay(id self,SEL sel,NSInteger reason){gCurrentFeedCell=self;IMP o=PTOriginalForSelf(self,sel);if(o)((void(*)(id,SEL,NSInteger))o)(self,sel,reason);TikTokPlusInstallMuteButton();if(gPrivateTikTokMuted)PTScanObject(self,0);}
static void PTControllerPlay(id self,SEL sel){gCurrentPlayerController=self;if(gPrivateTikTokMuted)PTForceObject(self);IMP o=PTOriginalForSelf(self,sel);if(o)((void(*)(id,SEL))o)(self,sel);if(gPrivateTikTokMuted)PTScanObject(self,0);}
static void InstallPrivateHooks(void){Class controller=NSClassFromString(@"AWEPlayVideoPlayerController");Class cell=NSClassFromString(@"AWEFeedCellViewController");if(!controller&&!cell)return;PTInstall(controller,@selector(playerWillLoopPlaying:),(IMP)PTPlayerLoop);PTInstall(controller,@selector(play),(IMP)PTControllerPlay);PTInstall(cell,@selector(playerWillLoopPlaying:),(IMP)PTPlayerLoop);PTInstall(cell,@selector(containerDidFullyDisplayWithReason:),(IMP)PTFeedDisplay);NSArray*b=@[@"setMuted:",@"setMute:",@"setAudioMuted:"];NSArray*f=@[@"setVolume:",@"setAudioVolume:",@"setPlayerVolume:"];if(controller){for(NSString*n in b)PTInstall(controller,NSSelectorFromString(n),(IMP)PTSetBool);for(NSString*n in f)PTInstall(controller,NSSelectorFromString(n),(IMP)PTSetFloat);PTInstall(controller,@selector(mute),(IMP)PTMute);}if(cell){for(NSString*n in b)PTInstall(cell,NSSelectorFromString(n),(IMP)PTSetBool);for(NSString*n in f)PTInstall(cell,NSSelectorFromString(n),(IMP)PTSetFloat);PTInstall(cell,@selector(mute),(IMP)PTMute);}}
static void PTApplyCurrent(void){if(!gPrivateTikTokMuted)return;PTForceObject(gCurrentPlayer);PTForceObject(gCurrentPlayerController);if([gCurrentPlayerController respondsToSelector:@selector(player)])PTForceObject(((id(*)(id,SEL))objc_msgSend)(gCurrentPlayerController,@selector(player)));if([gCurrentPlayerController respondsToSelector:@selector(currentPlayer)])PTForceObject(((id(*)(id,SEL))objc_msgSend)(gCurrentPlayerController,@selector(currentPlayer)));PTScanObject(gCurrentFeedCell,0);PTScanObject(gCurrentPlayerController,0);PTScanObject(gCurrentPlayer,0);}
%ctor{if(!PTIsTikTok())return;gOriginalIMPs=[NSMutableDictionary dictionary];dispatch_async(dispatch_get_main_queue(),^{[[NSNotificationCenter defaultCenter]addObserverForName:@"TikTokPlusMuteChanged" object:nil queue:[NSOperationQueue mainQueue] usingBlock:^(NSNotification*n){gPrivateTikTokMuted=[n.userInfo[@"muted"]boolValue];if(gPrivateTikTokMuted)PTApplyCurrent();}];});dispatch_source_t timer=dispatch_source_create(DISPATCH_SOURCE_TYPE_TIMER,0,0,dispatch_get_main_queue());dispatch_source_set_timer(timer,dispatch_time(DISPATCH_TIME_NOW,NSEC_PER_SEC),NSEC_PER_SEC,100*NSEC_PER_MSEC);dispatch_source_set_event_handler(timer,^{InstallPrivateHooks();TikTokPlusInstallMuteButton();if(gPrivateTikTokMuted)PTApplyCurrent();});dispatch_resume(timer);}
